export default [{   
    name: "Ra",
    pantheons: ["Egyptian"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Horus",
    pantheons: ["Egyptian"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Isis",
    pantheons: ["Egyptian"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Thoth",
    pantheons: ["Egyptian"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Zues",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Hera",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Artemis",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Apollo",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Gaia",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Hermes",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Aphrodite",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Ares",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Hades",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Posiedon",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Iris",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Mercury (Diety)",
    pantheons: ["Roman"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Venus (Diety)",
    pantheons: ["Roman"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Mars (Diety)",
    pantheons: ["Roman"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Jupiter (Diety)",
    pantheons: ["Roman"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Saturn (Diety)",
    pantheons: ["Roman"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Neptune (Diety)",
    pantheons: ["Roman"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Pluto (Diety)",
    pantheons: ["Roman"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Brahma",
    pantheons: ["Hindi"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Vishnu",
    pantheons: ["Hindi"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Ganesh",
    pantheons: ["Hindi"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Shakti",
    pantheons: ["Hindi"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Kali",
    pantheons: ["Hindi"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Parvarti",
    pantheons: ["Hindi"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Krishna",
    pantheons: ["Hindi"],
    kind: "Dieties",
    otherSpellings: [""],
    description: "",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},{   
    name: "Dionysus",
    pantheons: ["Greek"],
    kind: "Dieties",
    otherSpellings: ["Dionysious"],
    description: "A mysterious & powerful greek god, on the surface, the god of Wine & Fertility, but also having connections to divine ectasy and inspiration.",
    thumbnail: "", images: [],
    backgroundInfo: "", meaningInfo:"", number: null, 
},
{   
    name: "Shiva",
    pantheons: ["Hindi"],
    kind: "Dieties",
    otherSpellings: ["Shiv"],
    description: "One of the three major Gods of the Hindi religions, the god of Wisdom & Destruction",
    thumbnail: "", images: [""],
    backgroundInfo: "", meaningInfo:"", number: null 
},
]